=begin
#Iterable API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.8

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.32
=end

require 'spec_helper'
require 'json'

# Unit tests for Iterable::CommerceApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CommerceApi' do
  before do
    # run before each test
    @instance = Iterable::CommerceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CommerceApi' do
    it 'should create an instance of CommerceApi' do
      expect(@instance).to be_instance_of(Iterable::CommerceApi)
    end
  end

  # unit tests for track_purchase
  # Track a purchase
  # Track purchase events. &#x27;shoppingCartItems&#x27; field on the user profile is cleared. User profile is also updated if it already exists (created otherwise) using the user request field. Also, note that there is a soft limit on the number of unique fields a user can have (default is 1,000). Types of data fields must match the types sent in previous requests, across all data fields in the project.
  # @param body purchase data
  # @param [Hash] opts the optional parameters
  # @return [IterableApiResponse]
  describe 'track_purchase test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_cart
  # Update a user&#x27;s shopping cart items
  # Update the &#x27;shoppingCartItems&#x27; field on the user profile with shopping cart items. User profile is updated if it already exists (created otherwise) via the user field. Types of data fields must match the types sent in previous requests, across all data fields in the project.
  # @param body state of the cart
  # @param [Hash] opts the optional parameters
  # @return [IterableApiResponse]
  describe 'update_cart test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
