=begin
#Iterable API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.8

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.32
=end

require 'spec_helper'
require 'json'

# Unit tests for Iterable::EmailApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'EmailApi' do
  before do
    # run before each test
    @instance = Iterable::EmailApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EmailApi' do
    it 'should create an instance of EmailApi' do
      expect(@instance).to be_instance_of(Iterable::EmailApi)
    end
  end

  # unit tests for cancel
  # Cancel an email to a user
  # Cancel an email to a specific user. Must include either an email address AND campaignId, or just a scheduledMessageId.
  # @param body Email and Campaign ID
  # @param [Hash] opts the optional parameters
  # @return [IterableApiResponse]
  describe 'cancel test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for target
  # Send an email to an email address
  # Send an email to a specific email address. Request data fields will override user profile data fields. A reference to the user profile is provided via the &#x27;profile&#x27; field, to help resolve field collisions.
  # @param body Recipient and email id
  # @param [Hash] opts the optional parameters
  # @return [IterableApiResponse]
  describe 'target test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for view_in_browser
  # View a previously sent email
  # View a rendered version of a previously sent email. &lt;b&gt;Rate limit&lt;/b&gt;: 100 requests/second, per project.
  # @param message_id id of sent message
  # @param [Hash] opts the optional parameters
  # @option opts [String] :email user&#x27;s email
  # @option opts [String] :user_id user&#x27;s userId
  # @return [String]
  describe 'view_in_browser test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
