=begin
#Iterable API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.8

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.32
=end

require 'spec_helper'
require 'json'

# Unit tests for Iterable::ExportApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ExportApi' do
  before do
    # run before each test
    @instance = Iterable::ExportApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExportApi' do
    it 'should create an instance of ExportApi' do
      expect(@instance).to be_instance_of(Iterable::ExportApi)
    end
  end

  # unit tests for export_data_csv
  # Export data to CSV
  # Export campaign analytics data in CSV format. Use of either &#x27;range&#x27; or &#x27;startDateTime&#x27; and &#x27;endDateTime&#x27; is required.&lt;br/&gt;&lt;b&gt;Rate limit&lt;/b&gt;: 4 requests/minute, per project.
  # @param data_type_name data type name
  # @param [Hash] opts the optional parameters
  # @option opts [String] :range date range, uses UTC time
  # @option opts [String] :delimiter CSV filter delimiter
  # @option opts [String] :start_date_time Export starting from (&gt;&#x3D;) (yyyy-MM-dd HH:mm:ss [ZZ])
  # @option opts [String] :end_date_time Export ending at (&lt;) (yyyy-MM-dd HH:mm:ss [ZZ])
  # @option opts [String] :omit_fields Fields to omit (comma separated)
  # @option opts [Array<String>] :only_fields If non-empty, will only export these fields
  # @option opts [Integer] :campaign_id If provided, only export data from this campaign
  # @return [String]
  describe 'export_data_csv test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for export_data_json
  # Export data to JSON
  # Export campaign analytics data in JSON format, one entry per line. Use of either &#x27;range&#x27; or &#x27;startDateTime&#x27; and &#x27;endDateTime&#x27; is required.&lt;br/&gt;&lt;b&gt;Rate limit&lt;/b&gt;: 4 requests/minute, per project.
  # @param data_type_name data type name
  # @param [Hash] opts the optional parameters
  # @option opts [String] :range date range, uses UTC time
  # @option opts [String] :start_date_time export starting from (&amp;gt;&#x3D;) (yyyy-MM-dd HH:mm:ss [ZZ])
  # @option opts [String] :end_date_time export ending at (&amp;lt;) (yyyy-MM-dd HH:mm:ss [ZZ])
  # @option opts [String] :omit_fields fields to omit (comma separated)
  # @option opts [Array<String>] :only_fields if nonempty, will only export these fields
  # @option opts [Integer] :campaign_id if provided, only export data from this campaign
  # @return [String]
  describe 'export_data_json test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for export_user_events
  # Export user events
  # Export all events in JSON format for a user. One event per line.
  # @param email email
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :include_custom_events Include Custom Events
  # @return [String]
  describe 'export_user_events test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
