=begin
#Iterable API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.8

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.32
=end

require 'spec_helper'
require 'json'

# Unit tests for Iterable::InAppApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InAppApi' do
  before do
    # run before each test
    @instance = Iterable::InAppApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InAppApi' do
    it 'should create an instance of InAppApi' do
      expect(@instance).to be_instance_of(Iterable::InAppApi)
    end
  end

  # unit tests for cancel
  # Cancel a scheduled in-app message
  # Cancels the sending of a scheduled in-app message to a specific user.
  # @param body Email and Campaign ID
  # @param [Hash] opts the optional parameters
  # @return [IterableApiResponse]
  describe 'cancel test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_messages
  # Get a user&#x27;s in-app messages
  # Get a user&#x27;s in-app messages. This endpoint always returns the user&#x27;s non-selective (not app-specific) in-app messages; to also fetch app-specific in-app messages, include a &lt;code&gt;packageName&lt;/code&gt; and &lt;code&gt;platform&lt;/code&gt; in the request. This endpoint returns new messages and messages that have already been saved to a mobile inbox, and each message has a &lt;code&gt;read&lt;/code&gt; field to indicate whether or not it has already been seen.
  # @param count The number of in-app messages to fetch.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :email The email address of the user for which to fetch in-app messages. Specify either an email or a userId.
  # @option opts [String] :user_id The userId of the user for which to fetch in-app messages. Specify either an email or a userId.
  # @option opts [String] :platform The platform of the app for which to retrieve selective in-app messages: iOS or Android (case-sensitive).
  # @option opts [String] :sdk_version Iterable SDK version (e.g., 6.2.17)
  # @option opts [String] :package_name The package name of the app for which to retrieve selective in-app messages.
  # @return [ApiInAppMessagesResponse]
  describe 'get_messages test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for target
  # Send an in-app notification to a user
  # Send an in-app notification to a specific user. Request data fields will override user profile data fields. A reference to the user profile is provided via the &#x27;profile&#x27; field, to help resolve field collisions.
  # @param body Recipient and email id
  # @param [Hash] opts the optional parameters
  # @return [IterableApiResponse]
  describe 'target test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
