=begin
#Iterable API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.8

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.32
=end

require 'spec_helper'
require 'json'

# Unit tests for Iterable::ListsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ListsApi' do
  before do
    # run before each test
    @instance = Iterable::ListsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ListsApi' do
    it 'should create an instance of ListsApi' do
      expect(@instance).to be_instance_of(Iterable::ListsApi)
    end
  end

  # unit tests for create
  # Create a static list
  # Create a new static list.
  # @param body name
  # @param [Hash] opts the optional parameters
  # @return [CreateListResponse]
  describe 'create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete
  # Delete a static list
  # Delete a static list by listId.
  # @param list_id list id
  # @param [Hash] opts the optional parameters
  # @return [IterableApiResponse]
  describe 'delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_list_count
  # Get count of users in list
  # Get the number of users within a list. &lt;b&gt;Rate limit&lt;/b&gt;: 5 requests/minute, per project.
  # @param list_id list id
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'get_list_count test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_lists
  # Get lists
  # Get all lists within a project. &lt;b&gt;Rate limit&lt;/b&gt;: 100 requests/second, per project.
  # @param [Hash] opts the optional parameters
  # @return [GetListsResponse]
  describe 'get_lists test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_lists_0
  # Get users in a list
  # Get all users within a list. &lt;b&gt;Rate limit&lt;/b&gt;: 5 requests/minute, per project.
  # @param list_id list id
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'get_lists_0 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for subscribe
  # Add subscribers to list
  # Add specific subscribers to a list.
  # @param body email list id and list of emails
  # @param [Hash] opts the optional parameters
  # @return [ListResponse]
  describe 'subscribe test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for unsubscribe
  # Remove users from a list
  # Remove specific users from a list.
  # @param body email list id and list of emails
  # @param [Hash] opts the optional parameters
  # @return [ListResponse]
  describe 'unsubscribe test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
