=begin
#Iterable API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.8

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.32
=end

require 'spec_helper'
require 'json'

# Unit tests for Iterable::MessageTypesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MessageTypesApi' do
  before do
    # run before each test
    @instance = Iterable::MessageTypesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MessageTypesApi' do
    it 'should create an instance of MessageTypesApi' do
      expect(@instance).to be_instance_of(Iterable::MessageTypesApi)
    end
  end

  # unit tests for message_types
  # List message types
  # List all message types within a project. &lt;b&gt;Rate limit&lt;/b&gt;: 100 requests/second, per project.
  # @param [Hash] opts the optional parameters
  # @return [MessageTypesResponse]
  describe 'message_types test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
