=begin
#Iterable API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.8

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.32
=end

require 'spec_helper'
require 'json'

# Unit tests for Iterable::MetadataApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MetadataApi' do
  before do
    # run before each test
    @instance = Iterable::MetadataApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MetadataApi' do
    it 'should create an instance of MetadataApi' do
      expect(@instance).to be_instance_of(Iterable::MetadataApi)
    end
  end

  # unit tests for delete
  # Delete a table
  # Asynchronous. Deletes the table. 200 response indicates a valid request that will be processed; table may not be deleted immediately. Use GET /api/metadata/{table} to verify completion.
  # @param table Table name [Alphanumeric, case insensitive]
  # @param [Hash] opts the optional parameters
  # @return [IterableApiResponse]
  describe 'delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_0
  # Delete a single metadata key/value
  # Asynchronous. Deletes the specified item from the table. 200 response indicates a valid request that will be processed; data may not be deleted immediately. Use GET /api/metadata/{table}/{key} to verify completion.
  # @param table Table name [Alphanumeric, case insensitive]
  # @param key Metadata key [Alphanumeric, case sensitive]
  # @param [Hash] opts the optional parameters
  # @return [IterableApiResponse]
  describe 'delete_0 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get
  # Get the metadata value of a single key
  # @param table Table name [Alphanumeric, case insensitive]
  # @param key Metadata key [Alphanumeric, case sensitive]
  # @param [Hash] opts the optional parameters
  # @return [MetadataWithProperties]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list
  # List keys in a table
  # @param table Table name [Alphanumeric, case insensitive]
  # @param [Hash] opts the optional parameters
  # @option opts [String] :next_marker next result set id; returned by previous search if more hits exist
  # @return [Listing]
  describe 'list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_tables
  # List available tables
  # @param [Hash] opts the optional parameters
  # @return [ListMetadataTablesResponse]
  describe 'list_tables test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put
  # Create or replace metadata
  # Asynchronous. Creates or replaces the item associated with the specified key. 200 response indicates a valid request that will be processed; updates may not be made immediately. Use GET /api/metadata/{table}/{key} to verify completion.
  # @param body Metadata properties
  # @param table Table name [Alphanumeric, case insensitive]
  # @param key Metadata key [Alphanumeric, case sensitive]
  # @param [Hash] opts the optional parameters
  # @return [IterableApiResponse]
  describe 'put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
