=begin
#Iterable API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.8

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.32
=end

require 'spec_helper'
require 'json'

# Unit tests for Iterable::WebPushApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WebPushApi' do
  before do
    # run before each test
    @instance = Iterable::WebPushApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebPushApi' do
    it 'should create an instance of WebPushApi' do
      expect(@instance).to be_instance_of(Iterable::WebPushApi)
    end
  end

  # unit tests for cancel
  # Cancel a web push notification to a user
  # Cancel a web push notification to a specific user. Must include either an email address AND campaignId, or just a scheduledMessageId.
  # @param body Email and Campaign ID
  # @param [Hash] opts the optional parameters
  # @return [IterableApiResponse]
  describe 'cancel test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for target
  # Send web push notification to user
  # Send a web push notification to a specific user. Request data fields will override user profile data fields. A reference to the user profile is provided via the &#x27;profile&#x27; field, to help resolve field collisions.
  # @param body Recipient and email id
  # @param [Hash] opts the optional parameters
  # @return [IterableApiResponse]
  describe 'target test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
