=begin
#Iterable API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.8

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.32
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Iterable::DeeplinkURI
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DeeplinkURI' do
  before do
    # run before each test
    @instance = Iterable::DeeplinkURI.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DeeplinkURI' do
    it 'should create an instance of DeeplinkURI' do
      expect(@instance).to be_instance_of(Iterable::DeeplinkURI)
    end
  end
  describe 'test attribute "ios"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "android"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
