=begin
#Iterable API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.8

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.32
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Iterable::DeviceInfo
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DeviceInfo' do
  before do
    # run before each test
    @instance = Iterable::DeviceInfo.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DeviceInfo' do
    it 'should create an instance of DeviceInfo' do
      expect(@instance).to be_instance_of(Iterable::DeviceInfo)
    end
  end
  describe 'test attribute "device_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "platform"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["iOS", "Android"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.platform = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "app_package_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
