=begin
#Iterable API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.8

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.32
=end

# Common files
require 'iterable/api_client'
require 'iterable/api_error'
require 'iterable/version'
require 'iterable/configuration'

# Models
require 'iterable/models/api_email_template_model'
require 'iterable/models/api_in_app_message'
require 'iterable/models/api_in_app_messages_response'
require 'iterable/models/api_in_app_template_model'
require 'iterable/models/api_push_template_model'
require 'iterable/models/api_sms_template_model'
require 'iterable/models/api_template_entry'
require 'iterable/models/api_template_response'
require 'iterable/models/api_user'
require 'iterable/models/api_user_update_request'
require 'iterable/models/api_webhook_model'
require 'iterable/models/api_webhook_response'
require 'iterable/models/bg_color'
require 'iterable/models/bulk_subscription_action_request'
require 'iterable/models/bulk_track_request'
require 'iterable/models/bulk_track_response'
require 'iterable/models/bulk_update_subscriptions_request'
require 'iterable/models/bulk_update_subscriptions_response'
require 'iterable/models/bulk_update_users_request'
require 'iterable/models/campaign_details'
require 'iterable/models/campaign_id_request'
require 'iterable/models/campaigns_response'
require 'iterable/models/cancel_scheduled_message_request___campaign_id_or_scheduled_message_id_are_required'
require 'iterable/models/catalog_bulk_delete_request'
require 'iterable/models/catalog_bulk_upload_request'
require 'iterable/models/catalog_field_definition_serialized_model'
require 'iterable/models/catalog_field_mappings_response'
require 'iterable/models/catalog_index_item_request'
require 'iterable/models/catalog_item_with_properties'
require 'iterable/models/catalog_mappings_update_request'
require 'iterable/models/catalog_name'
require 'iterable/models/catalog_update_item_request'
require 'iterable/models/channel_details'
require 'iterable/models/channels_response'
require 'iterable/models/client_template_id_response'
require 'iterable/models/commerce_item'
require 'iterable/models/create_campaign_request'
require 'iterable/models/create_campaign_response'
require 'iterable/models/create_list_request'
require 'iterable/models/create_list_response'
require 'iterable/models/deeplink_uri'
require 'iterable/models/device'
require 'iterable/models/device_info'
require 'iterable/models/disable_device_request'
require 'iterable/models/experiment_metrics_response'
require 'iterable/models/get_catalog_items_response'
require 'iterable/models/get_catalogs_response'
require 'iterable/models/get_events_response'
require 'iterable/models/get_forgotten_user_emails_response'
require 'iterable/models/get_lists_response'
require 'iterable/models/get_sent_messages_response'
require 'iterable/models/get_templates_response'
require 'iterable/models/get_user_fields_response'
require 'iterable/models/get_webhooks_response'
require 'iterable/models/in_app_click_request'
require 'iterable/models/in_app_close_request'
require 'iterable/models/in_app_consume_request'
require 'iterable/models/in_app_content_api'
require 'iterable/models/in_app_delivery_request'
require 'iterable/models/in_app_display_setting'
require 'iterable/models/in_app_display_settings'
require 'iterable/models/in_app_open_request'
require 'iterable/models/in_app_trigger'
require 'iterable/models/in_app_type_of_content'
require 'iterable/models/inbox_message_context'
require 'iterable/models/inbox_metadata'
require 'iterable/models/invalidate_jwt_request'
require 'iterable/models/iterable_api_response'
require 'iterable/models/js_object'
require 'iterable/models/js_value'
require 'iterable/models/link_param'
require 'iterable/models/list_details'
require 'iterable/models/list_metadata_tables_response'
require 'iterable/models/list_response'
require 'iterable/models/listing'
require 'iterable/models/message_context'
require 'iterable/models/message_medium'
require 'iterable/models/message_type_details'
require 'iterable/models/message_types_response'
require 'iterable/models/metadata_properties'
require 'iterable/models/metadata_with_properties'
require 'iterable/models/optional_api_user'
require 'iterable/models/position_option'
require 'iterable/models/put_metadata_request'
require 'iterable/models/register_browser_token_request'
require 'iterable/models/register_device_token_request'
require 'iterable/models/sent_message'
require 'iterable/models/string'
require 'iterable/models/subscribe_request'
require 'iterable/models/table'
require 'iterable/models/target_email_request'
require 'iterable/models/target_in_app_request'
require 'iterable/models/target_push_request'
require 'iterable/models/target_sms_request'
require 'iterable/models/target_web_push_request'
require 'iterable/models/track_purchase_request'
require 'iterable/models/track_push_open_request'
require 'iterable/models/track_request'
require 'iterable/models/trigger_campaign_request'
require 'iterable/models/trigger_workflow_request'
require 'iterable/models/tuple2'
require 'iterable/models/tuple2_string_js_value'
require 'iterable/models/unsubscribe_request'
require 'iterable/models/unsubscriber'
require 'iterable/models/update_cart_request'
require 'iterable/models/update_email_request'
require 'iterable/models/update_subscriptions_request'
require 'iterable/models/upsert_email_template_model'
require 'iterable/models/upsert_in_app_template_model'
require 'iterable/models/upsert_push_template_model'
require 'iterable/models/upsert_sms_template_model'
require 'iterable/models/user_request'
require 'iterable/models/user_response'
require 'iterable/models/value'
require 'iterable/models/web_in_app_display_settings'
require 'iterable/models/web_push_click_event_request'

# APIs
require 'iterable/api/campaigns_api'
require 'iterable/api/catalogs_api'
require 'iterable/api/channels_api'
require 'iterable/api/commerce_api'
require 'iterable/api/email_api'
require 'iterable/api/events_api'
require 'iterable/api/experiments_api'
require 'iterable/api/export_api'
require 'iterable/api/in_app_api'
require 'iterable/api/lists_api'
require 'iterable/api/message_types_api'
require 'iterable/api/metadata_api'
require 'iterable/api/push_api'
require 'iterable/api/sms_api'
require 'iterable/api/subscriptions_api'
require 'iterable/api/templates_api'
require 'iterable/api/users_api'
require 'iterable/api/web_push_api'
require 'iterable/api/webhooks_api'
require 'iterable/api/workflows_api'

module Iterable
  class << self
    # Customize default settings for the SDK using block.
    #   Iterable.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
